#!/usr/bin/env bash
# Configure redirection in Nginx default server block

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html

sed -i 's/.*listen\(.*\)80;/    listen 80;/g' /etc/nginx/sites-available/default


sed -i '/^}/i \
    location /redirect_me { \
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    }' /etc/nginx/sites-available/default

sudo service nginx restart
