#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend http_front
    bind *:80
    mode http
    default_backend my_backend

backend my_backend
    balance roundrobin
    server 524514-web-01 18.234.105.208:80 check
    server 524514-web-02 18.204.10.184:80 check

EOF

sudo echo "ENABLED=1" > /etc/default/haproxy

sudo systemctl restart haproxy
