#!/usr/bin/env bash
# check why Ubuntu container’s Nginx installation is notlistening on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
