#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# script only display:
# username
# user id
# Home directory path for the user

file_path="/etc/passwd"
while read -r line; do
    echo $line | cut -d ':' -f1,3,6
done < "$file_path"
