#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# script only displays:
# username
# user id
# Home directory path for the user

file_path="/etc/passwd"
while IFS=':' read -r username _ uid _ _ homedir _; do
    echo "$username:$uid:$homedir"
done < "$file_path"
