#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS

file_path="/etc/passwd"
while IFS=':' read -r username password uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $commandshell. $uid's place is protected by the passcode $password, more info about the user here: $uidinfo"
done < "$file_path"
