#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.

log_file="apache-access.log"
awk '{ip_code[$1, $9]++} END {for (key in ip_code) print ip_code[key], key}'
"$log_file" | sort -nr
