#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and displays this data
# exact format must be:
# OCCURENCE_NUMBER IP HTTP_CODE
# greatest to the lowest number of occurrences

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
