#!/usr/bin/env bash
# Displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line

count=1
while [ $count -lt 10 ]; do
    if [ $count -eq 9 ]; then
	echo -e "Best School\nHi"
    fi
	echo "Best school"
	((count++))
done
