#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it’s executed on
# ifconfig command:
# ifconfig -a | grep "inet addr" | cut -d " " -f12 | cut -d ":" -f2

ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f1
