#!/usr/bin/env bash

# Connect to a server without typing a password
# Configure using the private key ~/.ssh/school
# Refuse to authenticate using a password

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
